### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by dfallow** [FUKA-INNOVATIONS/Safeye#39]
- [x] Prototype Notifications
Send Notifications/Alert to selected trusted contacts:
- [x] Complete #40 -> When tracking mode is activated
- [x] Complete #41 -> When panic button is pressed
- [x] Complete #41 -> When safe button is pressed

**Comment by leinonenko** [comment]
After research:
- to set up push notifications, you need an Apple Push Notification key (APNs)
- to get it we need to have an apple developer account
- as an option, there are also local notifications, but I'm not sure how they can be implemented via firebase
- might ask tomorrow Juha

**Comment by leinonenko** [comment]
Local notification now works after activating panic mode, even if the phone is locked
The next goal is to enable notifications for other users through the database

**Comment by leinonenko** [comment]
Issue can be closed after solving all conflicts while merging, but in the future, if there is time, it will be possible to add a function at the entrance, which will offer to go to the settings by clicking the button if notifications are not allowed. I already have a prototype for that

...or even the application will not let the user pass further, as notifications are necessary for the full functionality of the application

**Comment by FUKA-INNOVATIONS** [comment]
Local notifications bugs fixed and integrated. I had to come up with a new solution for in-app notifications and that's also implemented and interacts with the database in real-time.
